# Automatically generated by configure - do not modify
SRC_PATH=/home/andrea/qasan/qemu/roms/seabios
AS=as
CCAS=clang-8
CC=clang-8
BCC=bcc
CPP=clang-8 -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
