#ifndef __QASAN_H__
#define __QASAN_H__

#include <stdio.h>
#include <unistd.h>

#define QASAN_VERSTR "0.1"

#ifdef DEBUG
#define QASAN_LOG(msg...) do { \
  if (__qasan_debug) { \
    fprintf(stderr, "==%d== ", getpid()); \
    fprintf(stderr, msg); \
  } \
} while (0)
#else
#define QASAN_LOG(msg...) do {} while (0)
#endif

#define QASAN_FAKESYS_NR 0xa2a4

enum {
  QASAN_ACTION_CHECK_LOAD,
  QASAN_ACTION_CHECK_STORE,
  QASAN_ACTION_MALLOC_USABLE_SIZE,
  QASAN_ACTION_MALLOC,
  QASAN_ACTION_CALLOC,
  QASAN_ACTION_REALLOC,
  QASAN_ACTION_POSIX_MEMALIGN,
  QASAN_ACTION_MEMALIGN,
  QASAN_ACTION_ALIGNED_ALLOC,
  QASAN_ACTION_VALLOC,
  QASAN_ACTION_PVALLOC,
  QASAN_ACTION_FREE,
  QASAN_ACTION_MEMCMP,
  QASAN_ACTION_MEMCPY,
  QASAN_ACTION_MEMMOVE,
  QASAN_ACTION_MEMSET,
  QASAN_ACTION_STRCHR,
  QASAN_ACTION_STRCASECMP,
  QASAN_ACTION_STRCAT,
  QASAN_ACTION_STRCMP,
  QASAN_ACTION_STRCPY,
  QASAN_ACTION_STRDUP,
  QASAN_ACTION_STRLEN,
  QASAN_ACTION_STRNCASECMP,
  QASAN_ACTION_STRNCMP,
  QASAN_ACTION_STRNCPY,
  QASAN_ACTION_STRNLEN,
};

extern int __qasan_debug;

#endif
